### ISSUE TITLE
About Diffusion

### ISSUE THREAD

**Issue by feifeitu1** [RohollahHS/BAD#1]
Hello, I have read your paper and find your ideas to be very innovative. 
But I have a small question that I hope you can clarify for me. It is regarding the diffusion part — which section does it appear in? It seems that I didn’t see any description of the related content in the paper. Could you help me with this? Thank you very much!

**Comment by RohollahHS** [comment]
Hi, thanks for your interest. We refer to our permuted corruption process as a way of diffusion, similar to the paper [Structured Denoising Diffusion Models in Discrete State-Spaces](https://arxiv.org/abs/2107.03006), which discusses masking as a diffusion process called absorbing diffusion. We can think of it as gradually corrupting the entire sequence in a dependent manner to a noise (in our case, multiple learnable absorbed states or mask tokens), in contrast to conventional diffusion processes, like [Denoising Diffusion Probabilistic Models](https://arxiv.org/abs/2006.11239), where diffusion is applied to each dimension (each pixel) independently.

Our corruption process is discussed in Section 2.2 of our paper in the **Corruption Process** part.

**Comment by feifeitu1** [comment]
Oh,Thank you very much for your reply.! I have a general understanding of your ideas now, and I will read that part of the paper in more detail.
